version: "3.9"
services:
  generator:
    build: 
      context: .
      dockerfile: generator/Dockerfile
    volumes: 
      - ./:/usr/src/app
      - ~/.aws:/root/.aws
    env_file: .env
  notifier:
    build: 
      context: .
      dockerfile: notifier/Dockerfile
    network_mode: "host"
    volumes: 
      - ./:/usr/src/app
      - ~/.aws:/root/.aws
    env_file: .env
