version: "3.9"
services:
  generator:
    build: ./generator
    volumes: 
      - ./:/usr/src/app
    environment:
      - POLL_INTERVAL_SECONDS=1
      - SQS_INPUT_QUEUE=https://sqs.eu-west-1.amazonaws.com/525027603511/pdfgen-input-20201231172114211100000001